apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
      - name: flask-webapp
        image: flask-webapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: flask-webapp-service
spec:
  type: NodePort
  selector:
    app: flask-webapp
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000