name: k8s-ci-cd

on: 
  push:
    branches:
      - main
  
jobs:
  k8s-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
        
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip 
            pip install -r flask-webapp/requirements.txt
            pip install pyyaml

      - name: Run tests
        run: pytest test/

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.14.0
        with:
          minikube version: "v1.33.1"
          kubernetes version: "v1.27.4"
          driver: docker

      # - name: Load Docker env for Minikube
      #   run: |
      #       echo "::group::Minikube Docker Environment"
      #       eval $(minikube docker-env)
      #       echo "::endgroup::"

      - name: Verify Minikube and Docker
        run: |
            docker version
            kubectl get nodes
      
      - name: Deploy to Minikube
        run: |
            python k8s.py

      - name: Point Docker CLI to Minikube
        run: |
            echo "$(minikube docker-env --shell=bash)"
            echo "DOCKER_HOST=$DOCKER_HOST" >> $GITHUB_ENV
            echo "DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY" >> $GITHUB_ENV
            echo "DOCKER_CERT_PATH=$DOCKER_CERT_PATH" >> $GITHUB_ENV

      - name: Debug K8s 
        run: |
            kubectl get pods -o wide
            kubectl describe pods
            for p in $(kubectl get pods -o name); do
              echo "--- Logs for $p ---"
              kubectl logs $p || true
            done

      - name: Wait for deployment
        run: |
            kubectl rollout status deployment/flask-webapp --timeout=20s

      - name: Shut service URL
        run: |
            minikube service flask-webapp-service --url

    