name: k8s-ci-cd

on: 
  push:
    branches:
      - main
  
jobs:
  k8s-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
        
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip 
            pip install -r flask-webapp/requirements.txt
            pip install pyyaml

      - name: Run tests
        run: pytest test/

      - name: Set up Minikube
        run: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            sudo install minikube /usr/local/bin/minikube
            minikube start --driver=docker
            eval $(minikube docker-env --shell=bash)
            echo "DOCKER_HOST=$DOCKER_HOST" >> $GITHUB_ENV
            echo "DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY" >> $GITHUB_ENV
            echo "DOCKER_CERT_PATH=$DOCKER_CERT_PATH" >> $GITHUB_ENV

      - name: Deploy to Minikube
        run: |
            python k8s.py

      - name: Shut service URL
        run: |
            minikube service flask-webapp-service --url

    