name: k8s-ci-cd

on: 
  push:
    branches:
      - main
  
jobs:
  k8s-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
        
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip 
            pip install -r flask-webapp/requirements.txt
            pip install pyyaml

      - name: Run tests
        run: pytest test/

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.14.0
        with:
          minikube-version: latest
          kubernetes-version: latest
          start-options: '--driver=docker'

      - name: Load Docker env for Minikube
        run: |
            echo "::group::Minikube Docker Environment"
            eval $(minikube docker-env)
            echo "::endgroup::"
      
      - name: Deploy to Minikube
        run: |
            python k8s.py

      - name: Shut service URL
        run: |
            minikube service flask-webapp-service --url

    