name: k8s-ci-cd

on: 
  push:
    branches:
      - main
  
jobs:
  k8s-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
        
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip 
            pip install -r requirements.txt
            pip install pyyaml

      - name: Run tests
        run: pytest test/

      - name: Set up Docker for Minikube
        run: |
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            sudo install minikube-linux-amd64 /usr/local/bin/minikube
            minikube start --driver=docker
            echo "::add-path::$(minikube -p minikube docker-env | grep DOCKER_HOST | cut -d'=' -f2)"

      - name: Deploy to Minikube
        run: |
            python k8s.py

      - name: Shut service URL
        run: |
            minikube service flask-webapp-service --url

    